<a href="https://colab.research.google.com/github/ysimonov/TensorFlow-Developer-Certificate-Course-Udemy/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook some fundamentals of Tensors will be covered

Outline:
* Introduction to tensors
* Getting information from tensors
* Manipulation of tensors
* Tensors & Numpy
* Using @tf.function to speed up python functions
* Using GPUs with TensorFlow


Introduction to Tensors

In [1]:
import tensorflow as tf
import tensorflow_probability as tfp
import numpy as np
print(tf.__version__)

2.8.2


In [ ]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check dimensions of the vector
vector.ndim

1

In [ ]:
# Create a matrix
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# Check dimensions of the matrix
matrix.ndim

2

In [ ]:
# Create another matrix with dtype
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What's been created so far using tf.constant():

* Scalar
* Vector
* Matrix
* Tensor

In [ ]:
# Create the same tensor with tf.Variable() as above
variable_tensor = tf.Variable([10, 7])
constant_tensor = tf.constant([10, 7])

variable_tensor, constant_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Change one of the elements in a variable tensor
variable_tensor[0] = 7
variable_tensor

TypeError: ignored

In [ ]:
# Try changing with assign
variable_tensor[0].assign(7)
variable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Try changing value in constant tensor
constant_tensor[0] = 7

TypeError: ignored

In [ ]:
constant_tensor[0].assign(7)

AttributeError: ignored

## Creating Random Tensors

Random tensors are tensors of some arbitrary size which contains random numbers

In [ ]:
# Create random tensors
tf.random.set_seed(42)
g = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = g.normal(shape=(3, 2))
random_2 = g.normal(shape=(3, 2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.17522676,  0.71105534],
        [ 0.54882437,  0.14896014],
        [-0.54757965,  0.61634356]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

### Shuffle the order of elements in a tensor


In [ ]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

# randomly shuffle along tensor's first dimension
tf.random.set_seed(42)
shuffled = tf.random.shuffle(not_shuffled, seed=42)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# samples has shape [1, 10], where each value is either 0 or 1 with equal
# probability.
samples = tf.random.categorical(tf.math.log([[0.5, 0.5]]), 10)
samples

<tf.Tensor: shape=(1, 10), dtype=int64, numpy=array([[1, 0, 0, 1, 0, 1, 0, 1, 1, 1]])>

In [ ]:
samples = tf.random.poisson([10], [0.5, 1.5])
samples

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[1., 2.],
       [0., 2.],
       [2., 3.],
       [0., 1.],
       [1., 2.],
       [0., 1.],
       [1., 0.],
       [2., 2.],
       [0., 1.],
       [0., 0.]], dtype=float32)>

### Rule 4: If both the graph-level and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [ ]:
# (without this flag randomness with be changed)
# tf.random.set_seed(42)  # global level random seed  
tf.random.shuffle(not_shuffled, seed=42)  # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tf.ones((5, 5))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
import numpy as np
tf.zeros((5, 5), dtype=np.int32)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)>

In [ ]:
print(np.int32 == tf.int32)

True


In [ ]:
np_arr = np.arange(1, 25, dtype=np.int32)
np_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
# create tensor from numpy and modify shape -> creates new memory if new shape
tf_arr = tf.constant(np_arr, shape=(2, 3, 4))
tf_arr

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
### Getting information from tensors
np_arr2 = np.random.rand(3, 4)
np_arr2

array([[0.53782097, 0.67139481, 0.86918536, 0.83771879],
       [0.87731358, 0.52303846, 0.27225854, 0.810171  ],
       [0.97451643, 0.98230397, 0.03474809, 0.17816899]])

In [ ]:
tf_arr2 = tf.Variable(np_arr2)
tf_arr2

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float64, numpy=
array([[0.53782097, 0.67139481, 0.86918536, 0.83771879],
       [0.87731358, 0.52303846, 0.27225854, 0.810171  ],
       [0.97451643, 0.98230397, 0.03474809, 0.17816899]])>

### Getting information from tensors

When dealing with tensors, be aware of the following attributes:

1.   Shape (tensor.shape)
2.   Rand (tensor.ndim)
3.   Axis or dimension (tensor[0], tensor[:, 1])
4.   Size (tf.size(tensor))





In [ ]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of the tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions: ", rank_4_tensor.ndim)
print("Shape of a tensor: ", rank_4_tensor.shape)
print("Number of elements along the 0-th axis: ", rank_4_tensor.shape[0])
print("Number of elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in the tensor: ", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions:  4
Shape of a tensor:  (2, 3, 4, 5)
Number of elements along the 0-th axis:  2
Number of elements along the last axis:  5
Total number of elements in the tensor:  120


### Indexing tensors
Tensors can be indexed just like Python lists


In [ ]:
# get first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# get the first element from each dimension from 
# each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Create a rank-2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
# Get the last item of each row of rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Add in extra dimension to our rank 2 tensor, but keeping same information
# Three dots means on every axis before the last one
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)  # -1 means expand last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Expand the zeros axis
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating tensors (tensor operatios)

**Basic operations**

`+`, `-`, `*`, `/`

In [ ]:
# Can add values to a tensor using an addition operator using numpy array
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [ ]:
# Division
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [ ]:
# There are also built-in tensorflow functions (this can be sped up on GPU)
tf.multiply(tensor, 10) # original tensor is still unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tf.divide(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [ ]:
tensor_float = tf.cast(tensor, dtype=tf.float32)

In [ ]:
tf.exp(tensor_float, 5)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.2026465e+04, 1.0966332e+03],
       [2.0085537e+01, 5.4598148e+01]], dtype=float32)>

In [ ]:
tf.cos(tensor_float)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.8390715 ,  0.75390226],
       [-0.9899925 , -0.6536436 ]], dtype=float32)>

### Matrix multiplication

In [ ]:
# Matrix multiplication in tensorflow
tf.matmul(tensor_float, tensor_float)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[121.,  98.],
       [ 42.,  37.]], dtype=float32)>

In [ ]:
# Matrix multiplication using @ operator
tensor_float @ tensor_float

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[121.,  98.],
       [ 42.,  37.]], dtype=float32)>

In [ ]:
# * operator simply does Hadamard product between two tensors
tensor_float * tensor_float

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[100.,  49.],
       [  9.,  16.]], dtype=float32)>

## In tensorflow `tf.math.` or `tf.linalg` can simply be written as alias `tf.`

There are two rules of tensors (or matrices) need to fulfill when multiplying:
1. The inner dimensions of tensors must match
2. The resulting tensor has the shape of the inner dimensions

In [ ]:
X = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]], dtype=tf.float32)
X.shape

TensorShape([3, 2])

In [ ]:
XT = tf.transpose(X)
XT.shape

TensorShape([2, 3])

In [ ]:
tf.matmul(X, XT)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[113., 143., 173.],
       [143., 181., 219.],
       [173., 219., 265.]], dtype=float32)>

In [ ]:
tf.matmul(XT, X)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[251., 278.],
       [278., 308.]], dtype=float32)>

In [ ]:
# Reshape shuffles elements to meet the shape, 
# while transpose permutes dimensions
tf.reshape(X, shape=(2, 3)), XT

(<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[ 7.,  8.,  9.],
        [10., 11., 12.]], dtype=float32)>,
 <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
 array([[ 7.,  9., 11.],
        [ 8., 10., 12.]], dtype=float32)>)

**The dot product**

Matrix multiplication can be done with dot product

* `tf.matmul()`
* `tf.tensordot()`

In [ ]:
# tensor contraction along a specific dimension
tf.tensordot(X, XT, axes=1)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[113., 143., 173.],
       [143., 181., 219.],
       [173., 219., 265.]], dtype=float32)>

In [ ]:
tf.tensordot(X, XT, axes=0) # same as outer product

<tf.Tensor: shape=(3, 2, 2, 3), dtype=float32, numpy=
array([[[[ 49.,  63.,  77.],
         [ 56.,  70.,  84.]],

        [[ 56.,  72.,  88.],
         [ 64.,  80.,  96.]]],


       [[[ 63.,  81.,  99.],
         [ 72.,  90., 108.]],

        [[ 70.,  90., 110.],
         [ 80., 100., 120.]]],


       [[[ 77.,  99., 121.],
         [ 88., 110., 132.]],

        [[ 84., 108., 132.],
         [ 96., 120., 144.]]]], dtype=float32)>

## Changing datatypes in TensorFlow

In [ ]:
tensor = tf.constant([1, 2, 3])
tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
tf.cast(tensor, tf.float32)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [ ]:
tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
tf.cast(tensor, tf.float32)

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [ ]:
tf.cast(tensor, tf.double)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([1., 2., 3.])>

In [ ]:
tf.cast(tensor, tf.uint16)

<tf.Tensor: shape=(3,), dtype=uint16, numpy=array([1, 2, 3], dtype=uint16)>

In [ ]:
tf.cast(tensor, tf.uint64)

<tf.Tensor: shape=(3,), dtype=uint64, numpy=array([1, 2, 3], dtype=uint64)>

### Aggregating tensors

Aggregating tensors = condensing them from multiple values down to a smaller amount of values

In [ ]:
# Get the absolute values
D = tf.constant([-7, -10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# get the absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Going through following forms of aggregation:
* minimum
* maximum
* mean
* sum

In [ ]:
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([27, 77, 75, 21, 33, 72, 14, 64, 40, 21, 15, 69, 19, 15, 95, 79, 79,
       31, 34, 85, 16, 93, 35, 87, 63, 62, 21, 43,  3, 65, 93, 27, 32, 52,
       81,  6,  4, 93,  8, 42, 77, 15, 53, 83, 26,  6, 54, 44, 96, 87])>

In [ ]:
# Minimum of a tensor
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [ ]:
# Maximum of a tensor
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [ ]:
# Mean of a tensor
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=48>

In [ ]:
# Sum of a tensor
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2432>

### Finding Variance and standard deviation of a tensor

In [ ]:
# Variance
tf.math.reduce_variance(tf.cast(E, tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=877.5>

In [ ]:
# Standard deviation
tf.math.reduce_std(tf.cast(E, tf.float16))

<tf.Tensor: shape=(), dtype=float16, numpy=29.62>

In [ ]:
np.sqrt(877.5)

29.62262648719725

In [ ]:
# Find median of a tensor
tfp.stats.percentile(tf.cast(E, tf.float16), 50., interpolation='midpoint')

<tf.Tensor: shape=(), dtype=float16, numpy=43.5>

### Find the positional maximum and minimum

In [ ]:
# Create a new test tensor
tf.random.set_seed(42)
F = tf.random.uniform(shape=(50,))
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Find the positional maximum
imax = tf.argmax(F)
F[imax]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
tf.reduce_max(F) == F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
imin = tf.argmin(F)
imin, F[imin]

(<tf.Tensor: shape=(), dtype=int64, numpy=16>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>)

In [ ]:
FF = tf.random.normal(shape=(5, 5))
FF

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.00924649, -0.66206276, -0.7410269 ,  1.1985261 ,  0.8636208 ],
       [ 0.39257562,  0.93457496, -0.16017465, -2.1050534 ,  1.3769718 ],
       [ 0.43683258,  0.0760811 , -0.3780425 , -0.15550406, -0.90393233],
       [ 0.9405351 ,  0.18276669, -0.83427954,  0.98789215, -0.5446364 ],
       [ 1.7238988 ,  1.0708357 ,  0.4075437 , -1.0892357 , -0.87182766]],
      dtype=float32)>

In [ ]:
imin1 = tf.argmin(FF, axis=0) # finds minimum across columns
imin2 = tf.argmin(FF, axis=1) # finds minimum across rows

imin1, imin2

(<tf.Tensor: shape=(5,), dtype=int64, numpy=array([0, 0, 3, 1, 2])>,
 <tf.Tensor: shape=(5,), dtype=int64, numpy=array([2, 3, 4, 2, 3])>)

### Squeezing a tensor (removing all single dimensions)

In [ ]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=(50,)), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
tf.squeeze(G) # removes dimensions of size 1 from the shape of a tensor

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

### One-hot encoding of tensors

In [ ]:
# Create a list of indices
some_list = [0, 1, 2, 3]  # each position can correspond to red, green, blue, purple

encoding = tf.one_hot(some_list, depth=len(some_list))
encoding

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom values for one hot encoding
tf.one_hot(
    some_list, 
    depth=4, 
    on_value='yo I love deep learning', 
    off_value='I also like to dance'
)

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo I love deep learning', b'I also like to dance',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'yo I love deep learning',
        b'I also like to dance', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'yo I love deep learning', b'I also like to dance'],
       [b'I also like to dance', b'I also like to dance',
        b'I also like to dance', b'yo I love deep learning']],
      dtype=object)>

In [ ]:
tf.one_hot(
    some_list, 
    depth=2
)

<tf.Tensor: shape=(4, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
tf.one_hot(
    some_list, 
    depth=5
)

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]], dtype=float32)>

### Common mathematical operations

In [ ]:
H = tf.range(1, 10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Square of all numbers
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Square root
tf.sqrt(tf.cast(H, tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [ ]:
# Find the logarithm
tf.math.log(tf.cast(H, tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

In [ ]:
# Find the exponent
tf.math.exp(tf.cast(H, tf.float16), 3)

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([2.719e+00, 7.391e+00, 2.008e+01, 5.459e+01, 1.484e+02, 4.035e+02,
       1.097e+03, 2.980e+03, 8.104e+03], dtype=float16)>

### Tensors and Numpy arrays

Tensorflow interacts well with numpy arrays. 

🔑 The default data type of float Tensorflow Tensor is float32, while Numpy array is float64!

In [2]:
# Create a tensor directly from numpy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [3]:
# Convert tensor back to Numpy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [4]:
# Convert tensor J to Numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [5]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [6]:
# The default types are slightly different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])

# Check datatypes
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

### Finding access to GPUs

In [1]:
import tensorflow as tf
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
 PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [2]:
!nvidia-smi

Mon Jul 25 12:41:28 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P8    11W /  70W |      3MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

**Note:** If you have access to CUDA-enabled GPU, TensorFlow will automatically use it whenever possible.