<a href="https://colab.research.google.com/github/ysimonov/TensorFlow-Developer-Certificate-Course-Udemy/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook some fundamentals of Tensors will be covered

Outline:
* Introduction to tensors
* Getting information from tensors
* Manipulation of tensors
* Tensors & Numpy
* Using @tf.function to speed up python functions
* Using GPUs with TensorFlow


Introduction to Tensors

In [2]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [3]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [4]:
# Check the number of dimensions of a tensor
scalar.ndim

0

In [5]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [6]:
# Check dimensions of the vector
vector.ndim

1

In [8]:
# Create a matrix
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [9]:
# Check dimensions of the matrix
matrix.ndim

2

In [12]:
# Create another matrix with dtype
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [13]:
another_matrix.ndim

2

In [14]:
# Create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [15]:
tensor.ndim

3

What's been created so far using tf.constant():

* Scalar
* Vector
* Matrix
* Tensor

In [17]:
# Create the same tensor with tf.Variable() as above
variable_tensor = tf.Variable([10, 7])
constant_tensor = tf.constant([10, 7])

variable_tensor, constant_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [18]:
# Change one of the elements in a variable tensor
variable_tensor[0] = 7
variable_tensor

TypeError: ignored

In [19]:
# Try changing with assign
variable_tensor[0].assign(7)
variable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [20]:
# Try changing value in constant tensor
constant_tensor[0] = 7

TypeError: ignored

In [21]:
constant_tensor[0].assign(7)

AttributeError: ignored

## Creating Random Tensors

Random tensors are tensors of some arbitrary size which contains random numbers

In [53]:
# Create random tensors
tf.random.set_seed(42)
g = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = g.normal(shape=(3, 2))
random_2 = g.normal(shape=(3, 2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.17522676,  0.71105534],
        [ 0.54882437,  0.14896014],
        [-0.54757965,  0.61634356]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

### Shuffle the order of elements in a tensor


In [51]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

# randomly shuffle along tensor's first dimension
tf.random.set_seed(42)
shuffled = tf.random.shuffle(not_shuffled, seed=42)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [61]:
# samples has shape [1, 10], where each value is either 0 or 1 with equal
# probability.
samples = tf.random.categorical(tf.math.log([[0.5, 0.5]]), 10)
samples

<tf.Tensor: shape=(1, 10), dtype=int64, numpy=array([[1, 0, 0, 1, 0, 1, 0, 1, 1, 1]])>

In [64]:
samples = tf.random.poisson([10], [0.5, 1.5])
samples

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[1., 2.],
       [0., 2.],
       [2., 3.],
       [0., 1.],
       [1., 2.],
       [0., 1.],
       [1., 0.],
       [2., 2.],
       [0., 1.],
       [0., 0.]], dtype=float32)>