<a href="https://colab.research.google.com/github/ysimonov/TensorFlow-Developer-Certificate-Course-Udemy/blob/main/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook some fundamentals of Tensors will be covered

Outline:
* Introduction to tensors
* Getting information from tensors
* Manipulation of tensors
* Tensors & Numpy
* Using @tf.function to speed up python functions
* Using GPUs with TensorFlow


Introduction to Tensors

In [1]:
import tensorflow as tf
print(tf.__version__)

2.8.2


In [ ]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check dimensions of the vector
vector.ndim

1

In [ ]:
# Create a matrix
matrix = tf.constant([[10, 7],
                      [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
# Check dimensions of the matrix
matrix.ndim

2

In [ ]:
# Create another matrix with dtype
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]]])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What's been created so far using tf.constant():

* Scalar
* Vector
* Matrix
* Tensor

In [ ]:
# Create the same tensor with tf.Variable() as above
variable_tensor = tf.Variable([10, 7])
constant_tensor = tf.constant([10, 7])

variable_tensor, constant_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Change one of the elements in a variable tensor
variable_tensor[0] = 7
variable_tensor

TypeError: ignored

In [ ]:
# Try changing with assign
variable_tensor[0].assign(7)
variable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# Try changing value in constant tensor
constant_tensor[0] = 7

TypeError: ignored

In [ ]:
constant_tensor[0].assign(7)

AttributeError: ignored

## Creating Random Tensors

Random tensors are tensors of some arbitrary size which contains random numbers

In [ ]:
# Create random tensors
tf.random.set_seed(42)
g = tf.random.Generator.from_seed(42) # set seed for reproducibility
random_1 = g.normal(shape=(3, 2))
random_2 = g.normal(shape=(3, 2))

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.17522676,  0.71105534],
        [ 0.54882437,  0.14896014],
        [-0.54757965,  0.61634356]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

### Shuffle the order of elements in a tensor


In [ ]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])

# randomly shuffle along tensor's first dimension
tf.random.set_seed(42)
shuffled = tf.random.shuffle(not_shuffled, seed=42)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# samples has shape [1, 10], where each value is either 0 or 1 with equal
# probability.
samples = tf.random.categorical(tf.math.log([[0.5, 0.5]]), 10)
samples

<tf.Tensor: shape=(1, 10), dtype=int64, numpy=array([[1, 0, 0, 1, 0, 1, 0, 1, 1, 1]])>

In [ ]:
samples = tf.random.poisson([10], [0.5, 1.5])
samples

<tf.Tensor: shape=(10, 2), dtype=float32, numpy=
array([[1., 2.],
       [0., 2.],
       [2., 3.],
       [0., 1.],
       [1., 2.],
       [0., 1.],
       [1., 0.],
       [2., 2.],
       [0., 1.],
       [0., 0.]], dtype=float32)>

### Rule 4: If both the graph-level and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

In [ ]:
# (without this flag randomness with be changed)
# tf.random.set_seed(42)  # global level random seed  
tf.random.shuffle(not_shuffled, seed=42)  # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tf.ones((5, 5))

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
import numpy as np
tf.zeros((5, 5), dtype=np.int32)

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)>

In [ ]:
print(np.int32 == tf.int32)

True


In [ ]:
np_arr = np.arange(1, 25, dtype=np.int32)
np_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
# create tensor from numpy and modify shape -> creates new memory if new shape
tf_arr = tf.constant(np_arr, shape=(2, 3, 4))
tf_arr

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
### Getting information from tensors
np_arr2 = np.random.rand(3, 4)
np_arr2

array([[0.53782097, 0.67139481, 0.86918536, 0.83771879],
       [0.87731358, 0.52303846, 0.27225854, 0.810171  ],
       [0.97451643, 0.98230397, 0.03474809, 0.17816899]])

In [ ]:
tf_arr2 = tf.Variable(np_arr2)
tf_arr2

<tf.Variable 'Variable:0' shape=(3, 4) dtype=float64, numpy=
array([[0.53782097, 0.67139481, 0.86918536, 0.83771879],
       [0.87731358, 0.52303846, 0.27225854, 0.810171  ],
       [0.97451643, 0.98230397, 0.03474809, 0.17816899]])>

### Getting information from tensors

When dealing with tensors, be aware of the following attributes:

1.   Shape (tensor.shape)
2.   Rand (tensor.ndim)
3.   Axis or dimension (tensor[0], tensor[:, 1])
4.   Size (tf.size(tensor))





In [ ]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape=[2, 3, 4, 5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of the tensor
print("Datatype of every element: ", rank_4_tensor.dtype)
print("Number of dimensions: ", rank_4_tensor.ndim)
print("Shape of a tensor: ", rank_4_tensor.shape)
print("Number of elements along the 0-th axis: ", rank_4_tensor.shape[0])
print("Number of elements along the last axis: ", rank_4_tensor.shape[-1])
print("Total number of elements in the tensor: ", tf.size(rank_4_tensor).numpy())

Datatype of every element:  <dtype: 'float32'>
Number of dimensions:  4
Shape of a tensor:  (2, 3, 4, 5)
Number of elements along the 0-th axis:  2
Number of elements along the last axis:  5
Total number of elements in the tensor:  120


### Indexing tensors
Tensors can be indexed just like Python lists


In [ ]:
# get first 2 elements of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# get the first element from each dimension from 
# each index except for the final one
rank_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Create a rank-2 tensor (2 dimensions)
rank_2_tensor = tf.constant([[10, 7],
                             [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
# Get the last item of each row of rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Add in extra dimension to our rank 2 tensor, but keeping same information
# Three dots means on every axis before the last one
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1)  # -1 means expand last axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Expand the zeros axis
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating tensors (tensor operatios)

**Basic operations**

`+`, `-`, `*`, `/`

In [2]:
# Can add values to a tensor using an addition operator using numpy array
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [3]:
# Multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [4]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [5]:
# Division
tensor / 10

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [8]:
# There are also built-in tensorflow functions (this can be sped up on GPU)
tf.multiply(tensor, 10) # original tensor is still unchanged

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [9]:
tf.add(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [10]:
tf.divide(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1. , 0.7],
       [0.3, 0.4]])>

In [13]:
tensor_float = tf.cast(tensor, dtype=tf.float32)

In [14]:
tf.exp(tensor_float, 5)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.2026465e+04, 1.0966332e+03],
       [2.0085537e+01, 5.4598148e+01]], dtype=float32)>

In [17]:
tf.cos(tensor_float)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.8390715 ,  0.75390226],
       [-0.9899925 , -0.6536436 ]], dtype=float32)>

### Matrix multiplication

In [22]:
# Matrix multiplication in tensorflow
tf.matmul(tensor_float, tensor_float)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[121.,  98.],
       [ 42.,  37.]], dtype=float32)>

In [23]:
# Matrix multiplication using @ operator
tensor_float @ tensor_float

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[121.,  98.],
       [ 42.,  37.]], dtype=float32)>

In [24]:
# * operator simply does Hadamard product between two tensors
tensor_float * tensor_float

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[100.,  49.],
       [  9.,  16.]], dtype=float32)>

## In tensorflow `tf.math.` or `tf.linalg` can simply be written as alias `tf.`

There are two rules of tensors (or matrices) need to fulfill when multiplying:
1. The inner dimensions of tensors must match
2. The resulting tensor has the shape of the inner dimensions